# ---- BASIS ----
name = "etherium-login"                 # nur klein, zahlen, -  (keine Leerzeichen!)
account_id = "20c270570eda3ae89ef7d7a6d2ca1c8f"    # aus Cloudflare Dashboard
workers_dev = true
main = "build/worker/shim.mjs"     # Entry-Point der gebauten Worker-Datei
compatibility_date = "2025-08-01"

# ---- BUILD (Rust -> WASM) ----
# Installiert Rust + worker-build im CI und baut dann das Projekt.
[build]
command = """
curl -sSf https://sh.rustup.rs | sh -s -- -y && \
. $HOME/.cargo/env && \
cargo install -q worker-build && \
worker-build --release
"""

# ---- KV BINDINGS (TOP-LEVEL, NICHT im [build]!) ----
kv_namespaces = [
  { binding = "SIWE_OIDC", id = "999bb2a57214404ba34634d91a84d81c" }
]

# ---- DURABLE OBJECTS ----
[durable_objects]
bindings = [
  { name = "SIWE-OIDC-CODES", class_name = "DOCodes" }
]

[[migrations]]
tag = "v1"
new_classes = ["DOCodes"]

# ---- ENV VARS ----
[vars]
BASE_URL = "https://etherium.kitsos.net"     # exakt deine spätere Subdomain
PROJECT_ID = "b31ec02f65138b70d5a5f0ebbd5d03bd"          # WalletConnect/Reown Project ID
# ETH_PROVIDER = "https://..."                  # optional eigener RPC
